# CodeRabbit Configuration
# Insurance Claim Records Management System with Spring Batch

# Language: English for all reviews and comments
language: en

# Enable early access features
early_access: true

# Review settings
reviews:
  # Review profile - how thorough should reviews be
  profile: chill  # Options: chill, assertive. Use 'chill' for learning, 'assertive' for production
  
  # Request changes for critical issues
  request_changes_workflow: true
  
  # Enable high-level summary
  high_level_summary: true
  
  # Poem style for summary (makes reviews more engaging)
  poem: true
  
  # Review focus areas specific to this project
  review_status: true
  
  # Collapse walkthrough in reviews
  collapse_walkthrough: true
  
  # Path-specific instructions - exclude files that don't need review
  path_instructions:
    - path: "src/main/java/**/model/**"
      instructions: |
        - Check that JPA entities have proper annotations (@Entity, @Id, @Column)
        - Verify relationships (@OneToMany, @ManyToOne) are correctly configured
        - Ensure equals() and hashCode() are implemented for entities with composite keys
        - Check for proper cascade types
    
    - path: "src/main/java/**/batch/processor/**"
      instructions: |
        - Verify that ItemProcessor implementations handle null values gracefully
        - Check for proper exception handling
        - Ensure processors follow Single Responsibility Principle
        - Validate that business logic is isolated from infrastructure concerns
        - Check performance implications for large datasets
    
    - path: "src/main/java/**/batch/reader/**"
      instructions: |
        - Verify ItemReader properly handles file parsing errors
        - Check for memory leaks with large files
        - Ensure proper resource cleanup (streams, readers)
        - Validate character encoding handling (UTF-8)
    
    - path: "src/main/java/**/batch/writer/**"
      instructions: |
        - Check for proper transaction handling
        - Verify batch writing is efficient (avoiding N+1 queries)
        - Ensure duplicate detection logic is correct
        - Validate error handling for database constraints
    
    - path: "src/main/java/**/service/**"
      instructions: |
        - Verify @Service annotation is present
        - Check for proper dependency injection
        - Ensure business logic doesn't leak into controllers
        - Validate exception handling and logging
    
    - path: "src/main/java/**/repository/**"
      instructions: |
        - Verify repository extends correct Spring Data interface
        - Check custom query methods follow naming conventions
        - Validate @Query annotations if used
        - Ensure proper indexing hints for performance
    
    - path: "src/main/java/**/controller/**"
      instructions: |
        - Verify REST endpoints follow best practices
        - Check for proper HTTP status codes
        - Ensure request/response DTOs are used (not entities)
        - Validate input validation (@Valid, @NotNull, etc.)
    
    - path: "src/main/java/**/config/**"
      instructions: |
        - Check Spring configuration beans are properly annotated
        - Verify no hardcoded values (use @Value or properties)
        - Ensure batch jobs are correctly configured
        - Validate transaction management setup
    
    - path: "src/main/resources/**"
      instructions: |
        - Check for sensitive data in application.properties
        - Verify database connection pools are properly configured
        - Ensure logging levels are appropriate
    
    - path: "**/*.yaml"
      instructions: "Verify YAML syntax and structure"
    
    - path: "pom.xml"
      instructions: |
        - Check for dependency version conflicts
        - Verify all dependencies have defined versions
        - Look for security vulnerabilities in dependencies
  
  # Don't review these paths to save review quota
  path_filters:
    - "!**/target/**"
    - "!**/.mvn/**"
    - "!**/.idea/**"
    - "!**/.git/**"
    - "!**/*.md"  # Skip markdown files
    - "!**/mvnw"
    - "!**/mvnw.cmd"

# Chat settings
chat:
  # Enable bot to respond to comments
  auto_reply: true

# Tools to disable (enable all for thorough reviews)
tools:
  # Static analysis tools
  shellcheck:
    enabled: false  # No shell scripts in this project
  
  ruff:
    enabled: false  # No Python in this project
  
  markdownlint:
    enabled: false  # Skip markdown files
  
  github-checks:
    enabled: true  # Enable GitHub integration
  
  yamllint:
    enabled: true  # Check YAML files

# IMPORTANT: Custom instructions for your specific project
# These tell CodeRabbit about your architecture and standards
tone_instructions: |
  - Be constructive and educational in tone
  - Explain WHY changes are suggested, not just WHAT to change
  - Provide code examples when suggesting improvements
  - Consider this is an academic/learning project

# Project-specific context
project_context: |
  This is a Spring Boot application that processes insurance claim reimbursements using Spring Batch.
  
  **Architecture:**
  - Spring Boot 3.x with Spring Batch
  - JPA/Hibernate for persistence
  - PostgreSQL/H2 database
  - Batch processing for CSV and JSON files
  - Multi-step ETL pipeline
  
  **Key Business Logic:**
  - Reads treatment products from CSV (medication reference data)
  - Processes dossier submissions from JSON
  - Validates dossier data
  - Maps treatments to reference medications
  - Calculates reimbursement amounts based on rates
  - Writes results to database
  
  **Critical Components:**
  1. DossierCompositeProcessor: Chains validation, mapping, and calculation
  2. ReimbursementService: Core business logic for calculations
  3. Batch readers/writers: Handle I/O operations
  4. JPA repositories: Database access layer
  
  **Code Quality Focus:**
  - Follow Spring Framework best practices
  - Maintain clear separation of concerns
  - Ensure batch performance for large datasets
  - Proper exception handling and logging
  - Transaction management correctness
  - Data validation at all layers

# Additional review instructions
additional_instructions: |
  **When reviewing this codebase, pay special attention to:**
  
  1. **Spring Batch Performance:**
     - Check chunk sizes are appropriate (currently 100 for CSV, 10 for JSON)
     - Verify no N+1 query problems in batch writers
     - Ensure readers don't load entire files into memory
  
  2. **Data Validation:**
     - All user inputs must be validated
     - Dossier validation logic is complete
     - Price calculations handle edge cases (negatives, nulls, zero)
  
  3. **Error Handling:**
     - Batch jobs should handle partial failures gracefully
     - Logging provides enough context for debugging
     - Exceptions don't expose sensitive data
  
  4. **Business Logic Correctness:**
     - Reimbursement calculations match requirements
     - Treatment mapping logic handles missing reference data
     - Duplicate detection works correctly
  
  5. **Code Organization:**
     - Follow package structure: model, repository, service, controller, batch
     - Each processor has single responsibility
     - No business logic in controllers or repositories
  
  6. **Database Concerns:**
     - Check for missing indexes on frequently queried fields
     - Verify cascade operations are intentional
     - Ensure proper transaction boundaries
  
  7. **Spring Boot Best Practices:**
     - Use constructor injection over field injection
     - Proper use of @Transactional
     - Configuration externalized to application.properties
     - Avoid circular dependencies
  
  8. **Testing Considerations:**
     - Suggest test cases for complex business logic
     - Point out edge cases that need testing
     - Recommend integration tests for batch jobs
  
  **What NOT to focus on:**
  - Minor formatting issues (Spring has formatters)
  - Overly academic patterns that hurt readability
  - Premature optimization
  
  **Teaching approach:**
  Since this appears to be an academic project, please:
  - Explain concepts clearly
  - Reference official Spring documentation
  - Suggest learning resources when relevant
  - Encourage best practices without being rigid